const TextTheme({
  TextStyle? displayLarge,
  TextStyle? displayMedium,
  TextStyle? displaySmall,
  this.headlineLarge,
  TextStyle? headlineMedium,
  TextStyle? headlineSmall,
  TextStyle? titleLarge,
  TextStyle? titleMedium,
  TextStyle? titleSmall,
  TextStyle? bodyLarge,
  TextStyle? bodyMedium,
  TextStyle? bodySmall,
  TextStyle? labelLarge,
  this.labelMedium,
  TextStyle? labelSmall,
  TextStyle? headline1,
  TextStyle? headline2,
  TextStyle? headline3,
  TextStyle? headline4,
  TextStyle? headline5,
  TextStyle? headline6,
  TextStyle? subtitle1,
  TextStyle? subtitle2,
  TextStyle? bodyText1,
  TextStyle? bodyText2,
  TextStyle? caption,
  TextStyle? button,
  TextStyle? overline,
}) : assert(
       (displayLarge == null && displayMedium == null && displaySmall == null && headlineMedium == null &&
           headlineSmall == null && titleLarge == null && titleMedium == null && titleSmall == null &&
           bodyLarge == null && bodyMedium == null && bodySmall == null && labelLarge == null && labelSmall == null) ||
       (headline1 == null && headline2 == null && headline3 == null && headline4 == null &&
           headline5 == null && headline6 == null && subtitle1 == null && subtitle2 == null &&
           bodyText1 == null && bodyText2 == null && caption == null && button == null && overline == null),
       'Cannot mix 2018 and 2021 terms in call to TextTheme() constructor.'
     ),
     displayLarge = displayLarge ?? headline1,
     displayMedium = displayMedium ?? headline2,
     displaySmall = displaySmall ?? headline3,
     headlineMedium = headlineMedium ?? headline4,
     headlineSmall = headlineSmall ?? headline5,
     titleLarge = titleLarge ?? headline6,
     titleMedium = titleMedium ?? subtitle1,
     titleSmall = titleSmall ?? subtitle2,
     bodyLarge = bodyLarge ?? bodyText1,
     bodyMedium = bodyMedium ?? bodyText2,
     bodySmall = bodySmall ?? caption,
     labelLarge = labelLarge ?? button,
     labelSmall = labelSmall ?? overline;